version: '3'
services:
  web:
    build: .
    env_file:
      - docker.env
    environment:
      - RENTBOT_GSHEETS_KEY_PATH=/tmp/gcp_key.json
    volumes:
      - "${HOST_GSHEETS_KEY_PATH}:/tmp/gcp_key.json"
      - "./app:/app"
    ports:
      - 5000:80
